language: haskell
ghc: 7.8
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - 'echo'
install:
  - 'echo'
script: 
  - 'sh tests/unit-tests.sh'
  - 'bash tests/acceptance-tests.sh'
