language: haskell
ghc: 7.8
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - cabal sandbox init
  - cabal sandbox add-source oauth2-server*
install:
  - cabal install oauth2-server oauth2-server-snap
script: 
  - 'cd oauth2-server ; cabal test ; cd ..'
  - 'cd oauth2-server-snap ; cabal test ; cd ..'
