language: haskell
ghc:
  - 7.8
  - 7.10
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - 'echo'
install:
  - 'echo'
script:
  - cabal configure --enable-tests && cabal build && cabal test
